version: '3.7'

services:
  app:
    build:
      context: ./php82
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ../laravel:/var/www  # Монтируем директорию laravel в контейнер
    networks:
      - app-network

  webserver:
    build:
      context: ./nginx  # Контекст сборки для nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ../laravel:/var/www  # Монтируем директорию laravel в контейнер
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
